const rawDrData = [
    {
        "DR_Name": "HSHD23",
        "Underlying": "Hang Seng HK Dividend ETF",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "ETF",
        "Industry": "ETF",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "N/A",
        "AI_Chain": "N/A",
        "Risk_Label": "ETF",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 20,
        "Underlying_Ticker": "3110.HK"
    },
    {
        "DR_Name": "HKEX23",
        "Underlying": "Hong Kong Exchanges",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Financials",
        "Industry": "Financial Data & Stock Exchanges",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 777,
        "Underlying_Ticker": "0388.HK"
    },
    {
        "DR_Name": "AIA23",
        "Underlying": "AIA Group",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Financials",
        "Industry": "Insurance",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Defensive",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 130,
        "Underlying_Ticker": "1299.HK"
    },
    {
        "DR_Name": "CMBANK23",
        "Underlying": "China Merchants Bank",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Financials",
        "Industry": "Bank",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Defensive",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 90,
        "Underlying_Ticker": "3968.HK"
    },
    {
        "DR_Name": "CHMOBILE23",
        "Underlying": "China Mobile",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Communications",
        "Industry": "Telecom Services",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Service&Network",
        "Risk_Label": "Defensive",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 130,
        "Underlying_Ticker": "0941.HK"
    },
    {
        "DR_Name": "MUFG23",
        "Underlying": "Mitsubishi UFJ Financial Group",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Financials",
        "Industry": "Bank",
        "Stock_Group": "Seven Samurai",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Defensive",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 250,
        "Underlying_Ticker": "8306.T"
    },
    {
        "DR_Name": "BABA23",
        "Underlying": "Alibaba Group",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Consumer Discretionary",
        "Industry": "Internet Retail",
        "Stock_Group": "Terrific Ten",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Cloud Hyperscalers",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 150,
        "Underlying_Ticker": "9988.HK"
    },
    {
        "DR_Name": "KUAISH23",
        "Underlying": "Kuaishou Technology",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Communications",
        "Industry": "Internet Content & Information",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 140,
        "Underlying_Ticker": "1024.HK"
    },
    {
        "DR_Name": "TME23",
        "Underlying": "Tencent Music Entertainment",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Communications",
        "Industry": "Internet Content & Information",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 160,
        "Underlying_Ticker": "1698.HK"
    },
    {
        "DR_Name": "TRIPCOM23",
        "Underlying": "Trip.com Group",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Consumer Discretionary",
        "Industry": "Travel Services",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 1000,
        "Underlying_Ticker": "9961.HK"
    },
    {
        "DR_Name": "KINGSOFT23",
        "Underlying": "Kingsoft Corporation",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Communications",
        "Industry": "Electronic Gaming & Multimedia",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 60,
        "Underlying_Ticker": "3888.HK"
    },
    {
        "DR_Name": "BIDU23",
        "Underlying": "Baidu Inc.",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Communications",
        "Industry": "Internet Content & Information",
        "Stock_Group": "Terrific Ten",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 210,
        "Underlying_Ticker": "9888.HK"
    },
    {
        "DR_Name": "TENCENT23",
        "Underlying": "Tencent Holdings",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Communications",
        "Industry": "Internet Content & Information",
        "Stock_Group": "Terrific Ten",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Cloud Hyperscalers",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 900,
        "Underlying_Ticker": "0700.HK"
    },
    {
        "DR_Name": "MEITUAN23",
        "Underlying": "Meituan",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Consumer Discretionary",
        "Industry": "Internet Retail",
        "Stock_Group": "Terrific Ten",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 160,
        "Underlying_Ticker": "3690.HK"
    },
    {
        "DR_Name": "POPMART23",
        "Underlying": "Pop Mart International",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Consumer Discretionary",
        "Industry": "Leisure",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 420,
        "Underlying_Ticker": "9992.HK"
    },
    {
        "DR_Name": "XIAOMI23",
        "Underlying": "Xiaomi Corporation",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Technology",
        "Industry": "Consumer Electronics",
        "Stock_Group": "Terrific Ten",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 83,
        "Underlying_Ticker": "1810.HK"
    },
    {
        "DR_Name": "ANTA23",
        "Underlying": "Anta Sports Products",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Consumer Discretionary",
        "Industry": "Leisure",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 160,
        "Underlying_Ticker": "2020.HK"
    },
    {
        "DR_Name": "SUSHI23",
        "Underlying": "FOOD & LIFE COMPANIES (Sushiro)",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Consumer Discretionary",
        "Industry": "Restaurants",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 332,
        "Underlying_Ticker": "3563.T"
    },
    {
        "DR_Name": "NINTENDO23",
        "Underlying": "Nintendo Co.",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Communications",
        "Industry": "Electronic Gaming & Multimedia",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Defensive",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 1130,
        "Underlying_Ticker": "7974.T"
    },
    {
        "DR_Name": "SANRIO23",
        "Underlying": "Sanrio Company",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Consumer Discretionary",
        "Industry": "Specialty Retail",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 136,
        "Underlying_Ticker": "8136.T"
    },
    {
        "DR_Name": "ASICS23",
        "Underlying": "ASICS Corporation",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Consumer Discretionary",
        "Industry": "Footwear & Accessories",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 340,
        "Underlying_Ticker": "7936.T"
    },
    {
        "DR_Name": "CN23",
        "Underlying": "ChinaAMC CSI 300 Index ETF",
        "Country": "China",
        "Exchange": "SSE",
        "Sector": "ETF",
        "Industry": "ETF",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "N/A",
        "AI_Chain": "N/A",
        "Risk_Label": "ETF",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 4,
        "Underlying_Ticker": "510330.SS"
    },
    {
        "DR_Name": "CNSTAR5023",
        "Underlying": "STAR 50 ETF",
        "Country": "China",
        "Exchange": "SSE",
        "Sector": "ETF",
        "Industry": "ETF",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "N/A",
        "AI_Chain": "N/A",
        "Risk_Label": "ETF",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 1,
        "Underlying_Ticker": "588000.SS"
    },
    {
        "DR_Name": "CHNXT5023",
        "Underlying": "ChiNext 50 ETF",
        "Country": "China",
        "Exchange": "SZSE",
        "Sector": "ETF",
        "Industry": "ETF",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "N/A",
        "AI_Chain": "N/A",
        "Risk_Label": "ETF",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 1,
        "Underlying_Ticker": "159682.SZ"
    },
    {
        "DR_Name": "SMIC23",
        "Underlying": "Semiconductor Manufacturing International (SMIC)",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "Terrific Ten",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Foundry",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 85,
        "Underlying_Ticker": "0981.HK"
    },
    {
        "DR_Name": "HUAHONG23",
        "Underlying": "Hua Hong Semiconductor",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Foundry",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 70,
        "Underlying_Ticker": "1347.HK"
    },
    {
        "DR_Name": "ADVANT23",
        "Underlying": "Advantest Corporation",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Technology",
        "Industry": "Semiconductor Equipment & Materials",
        "Stock_Group": "Seven Samurai",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Equipment",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 1477,
        "Underlying_Ticker": "6857.T"
    },
    {
        "DR_Name": "SOFTBANK23",
        "Underlying": "SoftBank Group",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Communications",
        "Industry": "Telecom Services",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Cloud Hyperscalers",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 527.5,
        "Underlying_Ticker": "9984.T"
    },
    {
        "DR_Name": "SENSE23",
        "Underlying": "SenseTime Group",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 4,
        "Underlying_Ticker": "0020.HK"
    },
    {
        "DR_Name": "TEL23",
        "Underlying": "Tokyo Electron",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Technology",
        "Industry": "Semiconductor Equipment & Materials",
        "Stock_Group": "Seven Samurai",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Equipment",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2710,
        "Underlying_Ticker": "8035.T"
    },
    {
        "DR_Name": "GIGA23",
        "Underlying": "GigaDevice Semiconductor",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Memory&Storage",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 300,
        "Underlying_Ticker": "3986.HK"
    },
    {
        "DR_Name": "NAURA23",
        "Underlying": "NAURA Technology Group",
        "Country": "China",
        "Exchange": "SZSE",
        "Sector": "Technology",
        "Industry": "Semiconductor Equipment & Materials",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Equipment",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 900,
        "Underlying_Ticker": "002371.SZ"
    },
    {
        "DR_Name": "KIOXIA23",
        "Underlying": "Kioxia Holdings",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Memory&Storage",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 1600,
        "Underlying_Ticker": "285A.T"
    },
    {
        "DR_Name": "BIREN23",
        "Underlying": "Shanghai Biren Technology",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 25,
        "Underlying_Ticker": "6082.HK"
    },
    {
        "DR_Name": "GDS23",
        "Underlying": "GDS Holdings",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Technology",
        "Industry": "Information Technology Services",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "Service&Network",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 70,
        "Underlying_Ticker": "9698.HK"
    },
    {
        "DR_Name": "ZAI23",
        "Underlying": "Zhipu AI (Knowledge Atlas)",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 400,
        "Underlying_Ticker": "2513.HK"
    },
    {
        "DR_Name": "CNSEMI23",
        "Underlying": "Global X China Semiconductor ETF",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "ETF",
        "Industry": "ETF",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "N/A",
        "AI_Chain": "N/A",
        "Risk_Label": "ETF",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 100,
        "Underlying_Ticker": "3191.HK"
    },
    {
        "DR_Name": "CATL23",
        "Underlying": "Contemporary Amperex Technology (CATL)",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Industrials",
        "Industry": "Electrical Equipment & Parts",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 250,
        "Underlying_Ticker": "3750.HK"
    },
    {
        "DR_Name": "KEYENCE23",
        "Underlying": "Keyence Corporation",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Technology",
        "Industry": "Scientific & Technical Instruments",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 5650,
        "Underlying_Ticker": "6861.T"
    },
    {
        "DR_Name": "ZIJIN23",
        "Underlying": "Zijin Mining Group",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Materials",
        "Industry": "Gold",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 65,
        "Underlying_Ticker": "2899.HK"
    },
    {
        "DR_Name": "GANFENG23",
        "Underlying": "Ganfeng Lithium Group",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Materials",
        "Industry": "Chemicals",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 100,
        "Underlying_Ticker": "1772.HK"
    },
    {
        "DR_Name": "UBTECH23",
        "Underlying": "UBTECH Robotics",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Industrials",
        "Industry": "Specialty Industrial Machinery",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 250,
        "Underlying_Ticker": "9880.HK"
    },
    {
        "DR_Name": "HORIZON23",
        "Underlying": "Horizon Robotics",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 16,
        "Underlying_Ticker": "9660.HK"
    },
    {
        "DR_Name": "FANUC23",
        "Underlying": "FANUC Corporation",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Industrials",
        "Industry": "Specialty Industrial Machinery",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 550,
        "Underlying_Ticker": "6954.T"
    },
    {
        "DR_Name": "CNROBOAI23",
        "Underlying": "Global X China Robotics & AI ETF",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "ETF",
        "Industry": "ETF",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "N/A",
        "AI_Chain": "N/A",
        "Risk_Label": "ETF",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 100,
        "Underlying_Ticker": "2807.HK"
    },
    {
        "DR_Name": "MSFT23",
        "Underlying": "Microsoft Corporation",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "Mag7",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Cloud Hyperscalers",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 5400,
        "Underlying_Ticker": "MSFT"
    },
    {
        "DR_Name": "GOOG23",
        "Underlying": "Alphabet Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Communications",
        "Industry": "Internet Content & Information",
        "Stock_Group": "Mag7",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Cloud Hyperscalers",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 4000,
        "Underlying_Ticker": "GOOG"
    },
    {
        "DR_Name": "AMZN23",
        "Underlying": "Amazon.com",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Consumer Discretionary",
        "Industry": "Internet Retail",
        "Stock_Group": "Mag7",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Cloud Hyperscalers",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 3000,
        "Underlying_Ticker": "AMZN"
    },
    {
        "DR_Name": "META23",
        "Underlying": "Meta Platforms",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Communications",
        "Industry": "Internet Content & Information",
        "Stock_Group": "Mag7",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 8400,
        "Underlying_Ticker": "META"
    },
    {
        "DR_Name": "NVDA23",
        "Underlying": "NVIDIA Corporation",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "Mag7",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2100,
        "Underlying_Ticker": "NVDA"
    },
    {
        "DR_Name": "TSLA23",
        "Underlying": "Tesla, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Consumer Discretionary",
        "Industry": "Auto Manufacturers",
        "Stock_Group": "Mag7",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 5200,
        "Underlying_Ticker": "TSLA"
    },
    {
        "DR_Name": "LRCX23",
        "Underlying": "Lam Research",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductor Equipment & Materials",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Equipment",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2600,
        "Underlying_Ticker": "LRCX"
    },
    {
        "DR_Name": "AMD23",
        "Underlying": "Advanced Micro Devices",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2400,
        "Underlying_Ticker": "AMD"
    },
    {
        "DR_Name": "AVGO23",
        "Underlying": "Broadcom Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 4400,
        "Underlying_Ticker": "AVGO"
    },
    {
        "DR_Name": "MRVL23",
        "Underlying": "Marvell Technology",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 1200,
        "Underlying_Ticker": "MRVL"
    },
    {
        "DR_Name": "MICRON23",
        "Underlying": "Micron Technology",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Memory&Storage",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 5000,
        "Underlying_Ticker": "MU"
    },
    {
        "DR_Name": "SNDK23",
        "Underlying": "Sandisk Corporation",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Computer Hardware",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Memory&Storage",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 8000,
        "Underlying_Ticker": "SNDK"
    },
    {
        "DR_Name": "SEAGATE23",
        "Underlying": "Seagate Technology",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Computer Hardware",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Memory&Storage",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 4800,
        "Underlying_Ticker": "STX"
    },
    {
        "DR_Name": "ANET23",
        "Underlying": "Arista Networks",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Technology",
        "Industry": "Computer Hardware",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Service&Network",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 1800,
        "Underlying_Ticker": "ANET"
    },
    {
        "DR_Name": "PLTR23",
        "Underlying": "Palantir Technologies",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 1900,
        "Underlying_Ticker": "PLTR"
    },
    {
        "DR_Name": "SNOW23",
        "Underlying": "Snowflake Inc.",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2200,
        "Underlying_Ticker": "SNOW"
    },
    {
        "DR_Name": "CEG23",
        "Underlying": "Constellation Energy",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Utilities",
        "Industry": "Utilities",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Energy&Power",
        "Risk_Label": "Defensive",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 4000,
        "Underlying_Ticker": "CEG"
    },
    {
        "DR_Name": "CCJ23",
        "Underlying": "Cameco Corporation",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Energy",
        "Industry": "Uranium",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Energy&Power",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 1600,
        "Underlying_Ticker": "CCJ"
    },
    {
        "DR_Name": "GEV23",
        "Underlying": "GE Vernova Inc.",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Industrials",
        "Industry": "Specialty Industrial Machinery",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Energy&Power",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 11000,
        "Underlying_Ticker": "GEV"
    },
    {
        "DR_Name": "VRT23",
        "Underlying": "Vertiv Holdings",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Industrials",
        "Industry": "Electrical Equipment & Parts",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Energy&Power",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 3400,
        "Underlying_Ticker": "VRT"
    },
    {
        "DR_Name": "FCX23",
        "Underlying": "Freeport-McMoRan",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Materials",
        "Industry": "Copper",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Cyclical",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 800,
        "Underlying_Ticker": "FCX"
    },
    {
        "DR_Name": "NEM23",
        "Underlying": "Newmont Corporation",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Materials",
        "Industry": "Gold",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Defensive",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 1600,
        "Underlying_Ticker": "NEM"
    },
    {
        "DR_Name": "LLY23",
        "Underlying": "Eli Lilly and Company",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Healthcare",
        "Industry": "Drug Manufacturers",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Defensive",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 10000,
        "Underlying_Ticker": "LLY"
    },
    {
        "DR_Name": "COIN23",
        "Underlying": "Coinbase Global, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Financials",
        "Industry": "Financial Data & Stock Exchanges",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2000,
        "Underlying_Ticker": "COIN"
    },
    {
        "DR_Name": "AMAT23",
        "Underlying": "Applied Materials, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductor Equipment & Materials",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Equipment",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2500,
        "Underlying_Ticker": "AMAT"
    },
    {
        "DR_Name": "KLAC23",
        "Underlying": "KLA Corporation",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductor Equipment & Materials",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Equipment",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 1000,
        "Underlying_Ticker": "KLAC"
    },
    {
        "DR_Name": "SYNP23",
        "Underlying": "Synopsys, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2500,
        "Underlying_Ticker": "SNPS"
    },
    {
        "DR_Name": "TER23",
        "Underlying": "Teradyne, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductor Equipment & Materials",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Equipment",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2000,
        "Underlying_Ticker": "TER"
    },
    {
        "DR_Name": "COHR23",
        "Underlying": "Coherent Corp.",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Technology",
        "Industry": "Scientific & Technical Instruments",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Service&Network",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2000,
        "Underlying_Ticker": "COHR"
    },
    {
        "DR_Name": "LITE23",
        "Underlying": "Lumentum Holdings Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Communication Equipment",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Service&Network",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 5000,
        "Underlying_Ticker": "LITE"
    },
    {
        "DR_Name": "ON23",
        "Underlying": "ON Semiconductor Corporation",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 500,
        "Underlying_Ticker": "ON"
    },
    {
        "DR_Name": "NVTS23",
        "Underlying": "Navitas Semiconductor Corporation",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 100,
        "Underlying_Ticker": "NVTS"
    },
    {
        "DR_Name": "INTEL23",
        "Underlying": "Intel Corporation",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 700,
        "Underlying_Ticker": "INTC"
    },
    {
        "DR_Name": "NBIS23",
        "Underlying": "Nebius Group N.V.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Communications",
        "Industry": "Internet Content & Information",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Cloud Hyperscalers",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 1000,
        "Underlying_Ticker": "NBIS"
    },
    {
        "DR_Name": "MP23",
        "Underlying": "MP Materials Corp.",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Materials",
        "Industry": "Other Industrial Metals & Mining",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "Raw Materials",
        "Risk_Label": "Cyclical",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 300,
        "Underlying_Ticker": "MP"
    },
    {
        "DR_Name": "RKLB23",
        "Underlying": "Rocket Lab Corporation",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Industrials",
        "Industry": "Aerospace & Defense",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 2000,
        "Underlying_Ticker": "RKLB"
    },
    {
        "DR_Name": "SOFI23",
        "Underlying": "SoFi Technologies, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Financials",
        "Industry": "Credit Services",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 100,
        "Underlying_Ticker": "SOFI"
    },
    {
        "DR_Name": "MELI23",
        "Underlying": "MercadoLibre, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Consumer Discretionary",
        "Industry": "Internet Retail",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 10000,
        "Underlying_Ticker": "MELI"
    },
    {
        "DR_Name": "BRKB23",
        "Underlying": "Berkshire Hathaway Inc.",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Financials",
        "Industry": "Insurance",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "Defensive",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": 3000,
        "Underlying_Ticker": "BRK-B"
    },
    {
        "DR_Name": "ASEMI23",
        "Underlying": "Global X Asia Semiconductor ETF",
        "Country": "Hong Kong",
        "Exchange": "HKEX",
        "Sector": "ETF",
        "Industry": "ETF",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "N/A",
        "AI_Chain": "N/A",
        "Risk_Label": "ETF",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 100,
        "Underlying_Ticker": "3119.HK"
    },
    {
        "DR_Name": "CDNS23",
        "Underlying": "Cadence Design Systems",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 2000,
        "Underlying_Ticker": "CDNS"
    },
    {
        "DR_Name": "CRDO23",
        "Underlying": "Credo Technology Group",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Service&Network",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 1000,
        "Underlying_Ticker": "CRDO"
    },
    {
        "DR_Name": "MPWR23",
        "Underlying": "Monolithic Power Systems",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 10000,
        "Underlying_Ticker": "MPWR"
    },
    {
        "DR_Name": "TSEMI23",
        "Underlying": "Tower Semiconductor",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Foundry",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 1000,
        "Underlying_Ticker": "TSEM"
    },
    {
        "DR_Name": "FABRINET23",
        "Underlying": "Fabrinet",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Technology",
        "Industry": "Electronic Components",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Advanced Packaging",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 4000,
        "Underlying_Ticker": "FN"
    },
    {
        "DR_Name": "ETN23",
        "Underlying": "Eaton Corporation",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Industrials",
        "Industry": "Specialty Industrial Machinery",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Energy&Power",
        "Risk_Label": "Cyclical",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 2000,
        "Underlying_Ticker": "ETN"
    },
    {
        "DR_Name": "OKLO23",
        "Underlying": "Oklo Inc.",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Utilities",
        "Industry": "Utilities",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "Energy&Power",
        "Risk_Label": "High Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": 400,
        "Underlying_Ticker": "OKLO"
    },
    {
        "DR_Name": "SYM23",
        "Underlying": "Symbotic Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Industrials",
        "Industry": "Specialty Industrial Machinery",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 200,
        "Underlying_Ticker": "SYM"
    },
    {
        "DR_Name": "IONQ23",
        "Underlying": "IonQ, Inc.",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Technology",
        "Industry": "Computer Hardware",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 500,
        "Underlying_Ticker": "IONQ"
    },
    {
        "DR_Name": "SPACEX23",
        "Underlying": "Space Exploration Technologies (SpaceX)",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Industrials",
        "Industry": "Aerospace & Defense",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": 1200,
        "Underlying_Ticker": "SPCX"
    },
    {
        "DR_Name": "Dell23",
        "Underlying": "Dell Technologies",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Technology",
        "Industry": "Computer Hardware",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Service&Network",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "DELL"
    },
    {
        "DR_Name": "ASTS23",
        "Underlying": "AST SpaceMobile, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Communication Equipment",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "ASTS"
    },
    {
        "DR_Name": "NOW23",
        "Underlying": "ServiceNow, Inc.",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "NOW"
    },
    {
        "DR_Name": "EOSE23",
        "Underlying": "Eos Energy Enterprises, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Industrials",
        "Industry": "Electrical Equipment & Parts",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Small-cap",
        "AI_Chain": "Energy&Power",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "EOSE"
    },
    {
        "DR_Name": "IBM23",
        "Underlying": "International Business Machines Corporation",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Technology",
        "Industry": "Information Technology Services",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "AI Software&Apps",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "IBM"
    },
    {
        "DR_Name": "RGTI23",
        "Underlying": "Rigetti Computing, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Computer Hardware",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "N/A",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "RGTI"
    },
    {
        "DR_Name": "QCOM23",
        "Underlying": "QUALCOMM Incorporated",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "QCOM"
    },
    {
        "DR_Name": "ALAB23",
        "Underlying": "Astera Labs, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductors",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Chip Design",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "ALAB"
    },
    {
        "DR_Name": "SMR23",
        "Underlying": "NuScale Power Corporation",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Industrials",
        "Industry": "Specialty Industrial Machinery",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "Energy&Power",
        "Risk_Label": "Cyclical",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "SMR"
    },
    {
        "DR_Name": "AAOI23",
        "Underlying": "Applied Optoelectronics, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Communication Equipment",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mid-cap",
        "AI_Chain": "Service&Network",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "AAOI"
    },
    {
        "DR_Name": "AMKR23",
        "Underlying": "Amkor Technology, Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Semiconductor Equipment & Materials",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Advanced Packaging",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "AMKR"
    },
    {
        "DR_Name": "TFME23",
        "Underlying": "Tongfu Microelectronics Co., Ltd.",
        "Country": "China",
        "Exchange": "SZSE",
        "Sector": "Technology",
        "Industry": "Semiconductor Equipment & Materials",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Advanced Packaging",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Moderate Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "002156.SZ"
    },
    {
        "DR_Name": "CRWV23",
        "Underlying": "CoreWeave Inc.",
        "Country": "United States",
        "Exchange": "NASDAQ",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Cloud Hyperscalers",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "N/A"
    },
    {
        "DR_Name": "SCREEN23",
        "Underlying": "SCREEN Holdings Co., Ltd.",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Technology",
        "Industry": "Semiconductor Equipment & Materials",
        "Stock_Group": "Seven Samurai",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Equipment",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "7735.T"
    },
    {
        "DR_Name": "IBIDEN23",
        "Underlying": "IBIDEN Co., Ltd.",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Technology",
        "Industry": "Electronic Components",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Advanced Packaging",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "4062.T"
    },
    {
        "DR_Name": "MURATA23",
        "Underlying": "Murata Manufacturing Co., Ltd.",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Technology",
        "Industry": "Electronic Components",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Raw Materials",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "6981.T"
    },
    {
        "DR_Name": "AJINO23",
        "Underlying": "Ajinomoto Co., Inc.",
        "Country": "Japan",
        "Exchange": "TSE",
        "Sector": "Consumer Staples",
        "Industry": "Packaged Foods",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Raw Materials",
        "Risk_Label": "Defensive",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "2802.T"
    },
    {
        "DR_Name": "YOFC23",
        "Underlying": "Yangtze Optical Fibre and Cable Joint Stock Limited Company",
        "Country": "China",
        "Exchange": "HKEX",
        "Sector": "Technology",
        "Industry": "Communication Equipment",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Large-cap",
        "AI_Chain": "Service&Network",
        "Risk_Label": "Stable Growth",
        "Risk_Level": "Low Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "6869.HK"
    },
    {
        "DR_Name": "ORCL23",
        "Underlying": "Oracle Corporation",
        "Country": "United States",
        "Exchange": "NYSE",
        "Sector": "Technology",
        "Industry": "Software",
        "Stock_Group": "N/A",
        "Market_Cap_Tier": "Mega-cap",
        "AI_Chain": "Cloud Hyperscalers",
        "Risk_Label": "High Growth",
        "Risk_Level": "High Risk",
        "Conversion_Ratio": "pending",
        "Underlying_Ticker": "ORCL"
    }
];
